send more upload information via headers
SAP/cloud-authorization-buildpack pull request #94
Opened 2024-08-15 12:58 UTC by d047491

2024-08-15 13:12 UTC, f-blass requested changes

2024-08-15 13:12 UTC, f-blass commented on pkg/supply/supply.go
> +			"X-Cf-Appname": vcapApp.ApplicationName,
Let's use a more generic name that also fits for other use cases, e.g. if we provide some functionality to upload via CAP or as a k8s job. E.g. just remove the _cf_ part? `X-App-Name` or `X-Appname` ?

2024-08-15 13:12 UTC, f-blass commented on pkg/supply/env/config.go
> +	Users            any      `json:"users"`
From what I can see, only the `ApplicationName` is used in the coding. Let's strip down the struct to what we need exactly, no need to parse the other values.

2024-08-15 13:12 UTC, f-blass commented on pkg/supply/env/config.go
> +func LoadVcapApplication(log *libbuildpack.Logger) (VcapApplication, error) {
This func always returns error = nil. Remove error return value?

2024-08-19 14:26 UTC, d047491 commented
commited suggested changes

2024-08-20 09:09 UTC, f-blass approved these changes

2024-08-20 10:21 UTC, merged